[package]
name = "todo"
version = "0.8.4"
edition = "2024"

[dependencies]
file_id = { package = "file-id", version = "0.2.3" }
rustyline = "18.0.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
